// Top-level build file where you can add configuration options common to all sub-projects/modules.
plugins {
    id 'com.android.application' version '8.12.3' apply false
    id 'com.android.library' version '8.12.3' apply false

    // CAMBIO IMPORTANTE: De 1.7.20 a 1.9.22 para solucionar el error de "Incompatible version"
    id 'org.jetbrains.kotlin.android' version '1.9.22' apply false

    // Actualización recomendada para el BOM de Firebase nuevo que usas
    id("com.google.gms.google-services") version "4.4.2" apply false
}